export default clients = [
    "1 - Sixt GmbH & Co. Autovermietung KG",
    "10 - Sixt SE",
    "14 - BLM Verwaltungs GmbH",
    "15 - Sixt VerwGes mbH & Co. Gamma Immobilien KG",
    "16 - Sixt VerwGes mbH & Co. Delta Immobilien KG",
    "17 - SXT Res- und Vertriebs-GmbH & Co. KG",
    "18 - Sigma Grundstücks- & Verw-GmbH & Co. Immo. KG",
    "27 - Sigma Grundstuecks- und Verwaltungs GmbH",
    "30 - Sixt B.V.",
    "31 - Sixt Beteiligungen GmbH & Co. Holding KG",
    "32 - Sixt VerwGes mbH & Co. Epsilon Immobilien KG",
    "35 - Sixt Belgium BV",
    "37 - Sixt Air GmbH",
    "38 - SIXT S.a.r.l.",
    "42 - Sixt rent a car Limited",
    "52 - Sixt Car Sales GmbH",
    "53 - SXT Telesales GmbH",
    "56 - Sixt Ventures GmbH",
    "60 - SIXT SAS",
    "61 - Nizza Mobility SARL",
    "62 - SIXTI SARL",
    "63 - SIXT Developpement SARL",
    "66 - Sixt RENT A CAR S.L.U.",
    "67 - United Rentalsystem SARL",
    "69 - SIXT SARL (Monaco)",
    "70 - Sixt AG",
    "75 - Sixt rent-a-car AG",
    "78 - Sixt Transatlantik GmbH",
    "79 - Smaragd International Holding GmbH",
    "80 - Sixt GmbH",
    "88 - Sixt Rent a Car L.L.C.",
    "639 - SXT V+R Verwaltungs GmbH",
    "700 - SIXT Asset and Finance SAS",
    "701 - Sixt Limousine SARL",
    "702 - Sixt Financial Services GmbH",
    "703 - Sixt Ride Verwaltungs GmbH",
    "704 - Sixt Ride GmbH & Co. KG",
    "705 - SXT Services GmbH & Co.KG",
    "706 - SXT Verwaltungs-GmbH",
    "707 - Sixt Ride Holding GmbH & Co. KG",
    "708 - SXT Beteiligungsverwaltungs GmbH",
    "710 - Rhonesaone Mobility SARL",
    "711 - Phocemoove SARL",
    "717 - SIXT Seine SARL",
    "718 - Bopobiloc SARL",
    "719 - SXT Dienstleistungen GmbH & Co. KG",
    "720 - SXT International Projects and Finance GmbH",
    "723 - SXT Projects and Finance GmbH",
    "724 - Sigma Pi Holding GmbH & Co. KG",
    "725 - Lightning Holding GmbH & Co. KG",
    "726 - Matterhorn Holding GmbH & Co. KG",
    "727 - Blueprint Holding GmbH & Co. KG",
    "728 - Velocity Holding GmbH & Co. KG",
    "729 - Rail Paris Mobility SARL",
    "730 - Eiffel City Rent SARL",
    "731 - Francilsud Location SARL",
    "732 - Capitole Autos SARL",
    "733 - Benezet Location SARL",
    "734 - Wezz Rent SARL",
    "735 - Eaux Vives Location SARL",
    "736 - Flash Holding GmbH & Co. KG",
    "737 - Speed Holding GmbH & Co. KG",
    "738 - Varmayol Rent SARL",
    "739 - Septentri Loc SARL",
    "740 - Azucarloc SARL",
    "741 - Sixt Rent A Car SRL",
    "744 - Sixt International Services GmbH",
    "745 - Sixt R+D Private Limited",
    "746 - Sixt Verwaltungs B.V.",
    "747 - 1501 NW 49 St 33309, LLC",
    "748 - Sixt Shack",
    "749 - Sixt Verwaltungs GmbH in Vösendorf",
    "750 - Sixt Beteiligungen GmbH",
    "752 - SXT Projects and Services GmbH",
    "753 - Sixt Ride Holding Verwaltungs GmbH",
    "754 - SXT DR Services GmbH",
    "757 - SXT Retina Lab Verwaltungs GmbH",
    "758 - SXT Retina Lab GmbH & Co. KG",
    "760 - Sixt GmbH",
    "761 - Atlic Rent SARL",
    "762 - Urbanizy Loc SARL",
    "763 - Akrimo Beteiligungs GmbH",
    "764 - AKRIMO GmbH & Co. KG",
    "766 - Sixt Limousine Switzerland AG",
    "767 - Sixt Canadian Holding GmbH",
    "771 - Brenoloc SARL",
    "772 - Sixt VerwGes mbH & Co. Sita Immobilien KG",
    "773 - Sixt Systems GmbH",
    "774 - Sixt Immobilien Beteiligungen GmbH",
    "776 - Ory Rent SARL",
    "777 - Mobimars SARL",
    "778 - Utilymoov SARL",
    "780 - Sixt Car Sales LLC",
    "781 - SIL CAP, LLC",
    "783 - Sixt Funding LLC",
    "784 - Sixt Fleet Transfer LLC",
    "785 - Sixt Funding Associate LLC",
    "786 - Tango International Holding GmbH",
    "788 - Sixt Franchise USA, LLC",
    "791 - Sixt Rent a Car Inc.",
    "792 - SXT Projects GmbH"
  ]